<Project>
  <PropertyGroup>
    <OutputPath>$(SolutionDir)build\$(Configuration)\</OutputPath>
    <IntermediateOutputPath>$(SolutionDir)obj\$(MSBuildProjectName)\$(Configuration)\</IntermediateOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
</Project>
