<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>RommPlugin.UI</RootNamespace>
    <AssemblyName>RommPlugin.UI</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\build\$(Configuration)\</OutputPath>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="Unbroken.LaunchBox.Plugins">
      <HintPath>..\lib\LaunchBox\Unbroken.LaunchBox.Plugins.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RommPlugin.Core\RommPlugin.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Forms\*.resx">
      <DependentUpon>%(Filename).cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\*.Designer.cs">
      <DependentUpon>%(Filename).cs</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
