<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>RommPlugin</RootNamespace>
    <AssemblyName>RommPlugin</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\build\$(Configuration)\</OutputPath>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="Unbroken.LaunchBox.Plugins">
      <HintPath>..\lib\LaunchBox\Unbroken.LaunchBox.Plugins.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RommPlugin.Core\RommPlugin.Core.csproj" />
    <ProjectReference Include="..\RommPlugin.UI\RommPlugin.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="app.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
